name: ridekaro
description: "A ride sharing app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Services
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0

  # Maps & Location Services
  google_maps_flutter: ^2.6.1
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  flutter_polyline_points: ^1.0.0
  google_maps_webservice: ^0.0.19

  # UI and HTTP
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"


dependency_overrides:
  http: ^1.2.1
